// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';

export function DeleteConnection(arg1:number):Promise<void>;

export function ListConnections():Promise<Array<store.Connection>>;

export function ListQuickCommands():Promise<Array<store.QuickCommand>>;

export function SSHConnect(arg1:number):Promise<main.ConnectResult>;

export function SSHDisconnect(arg1:string):Promise<void>;

export function SaveConnection(arg1:store.Connection):Promise<number>;
