// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteQuickCommand(arg1) {
  return window['go']['main']['App']['DeleteQuickCommand'](arg1);
}

export function DetectLocalHosts() {
  return window['go']['main']['App']['DetectLocalHosts']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListQuickCommands() {
  return window['go']['main']['App']['ListQuickCommands']();
}

export function LocalDelete(arg1) {
  return window['go']['main']['App']['LocalDelete'](arg1);
}

export function LocalListDir(arg1) {
  return window['go']['main']['App']['LocalListDir'](arg1);
}

export function LocalMkdir(arg1, arg2) {
  return window['go']['main']['App']['LocalMkdir'](arg1, arg2);
}

export function LocalRename(arg1, arg2) {
  return window['go']['main']['App']['LocalRename'](arg1, arg2);
}

export function RemoteDelete(arg1, arg2) {
  return window['go']['main']['App']['RemoteDelete'](arg1, arg2);
}

export function RemoteDownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteDownloadFile'](arg1, arg2, arg3);
}

export function RemoteDownloadToDir(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RemoteDownloadToDir'](arg1, arg2, arg3, arg4, arg5);
}

export function RemoteListDir(arg1, arg2) {
  return window['go']['main']['App']['RemoteListDir'](arg1, arg2);
}

export function RemoteMetrics(arg1) {
  return window['go']['main']['App']['RemoteMetrics'](arg1);
}

export function RemoteMkdir(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteMkdir'](arg1, arg2, arg3);
}

export function RemoteReadTextFile(arg1, arg2) {
  return window['go']['main']['App']['RemoteReadTextFile'](arg1, arg2);
}

export function RemoteRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteRename'](arg1, arg2, arg3);
}

export function RemoteStartDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RemoteStartDownload'](arg1, arg2, arg3, arg4);
}

export function RemoteStartDownloadDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteStartDownloadDir'](arg1, arg2, arg3);
}

export function RemoteStartUpload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RemoteStartUpload'](arg1, arg2, arg3, arg4);
}

export function RemoteStartUploadPath(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RemoteStartUploadPath'](arg1, arg2, arg3, arg4);
}

export function RemoteUploadFile(arg1, arg2) {
  return window['go']['main']['App']['RemoteUploadFile'](arg1, arg2);
}

export function RemoteUploadLocalFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteUploadLocalFile'](arg1, arg2, arg3);
}

export function RemoteWriteTextFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteWriteTextFile'](arg1, arg2, arg3);
}

export function RemoteWriteUploadChunk(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteWriteUploadChunk'](arg1, arg2, arg3);
}

export function SSHConnect(arg1) {
  return window['go']['main']['App']['SSHConnect'](arg1);
}

export function SSHDisconnect(arg1) {
  return window['go']['main']['App']['SSHDisconnect'](arg1);
}

export function SSHResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHResize'](arg1, arg2, arg3);
}

export function SSHStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHStart'](arg1, arg2, arg3);
}

export function SSHWrite(arg1, arg2) {
  return window['go']['main']['App']['SSHWrite'](arg1, arg2);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveQuickCommand(arg1) {
  return window['go']['main']['App']['SaveQuickCommand'](arg1);
}

export function SelectPrivateKeyPath() {
  return window['go']['main']['App']['SelectPrivateKeyPath']();
}
